# Help: `topgrade --config-reference` (displays https://github.com/topgrade-rs/topgrade/blob/main/config.example.toml)

[misc]
  assume_yes = true
  cleanup = true
  disable = [
    "containers",
    "git_repos",
    "node",
    "pnpm",
    "skills",
    "system",
    "uv",
    "yarn",
  ]
  display_time = false

[commands]
  "Skills" = 'cd "$HOME" && npx --yes skills update --global'
  "npm" = 'cd "$HOME" && npm update --location global --allow-remote=all'
