# Help: `topgrade --config-reference` (displays https://github.com/topgrade-rs/topgrade/blob/main/config.example.toml)

[misc]
  assume_yes = true
  cleanup = true
  disable = ["containers", "git_repos", "node", "pnpm", "yarn", "uv"]
  display_time = false

[commands]
  "npm" = "npm update --location global --force"
