tap "homebrew/bundle"
tap "homebrew/core"

brew "awscli" 
brew "coreutils"
brew "diff-so-fancy"
brew "dockutil"
brew "git"
brew "git-extras"
brew "gnu-sed", args: ["with-default-names"]
brew "grep", args: ["with-default-names"]
brew "imagemagick"
brew "m-cli"
brew "mackup"
brew "mariadb"
brew "postgresql@9.6"
brew "redis"
brew "watchman"
brew "wget"
