tap "lotyp/homebrew-formulae"

# core/dotfiles
brew "coreutils"
brew "duti"
brew "lotyp/formulae/dockutil"
brew "mackup"
brew "nano"
brew "parallel"
brew "stow"
brew "thefuck"
brew "tmux"
brew "topgrade"
brew "util-linux"
brew "watch"

# fs/network
brew "bat"
# brew "croc"
brew "croc"
brew "curl"
brew "eza"
brew "httpie"
brew "ssh-copy-id"
brew "tree"
brew "unar"
brew "wget"
brew "zoxide"

# search/grep/diff
brew "diff-so-fancy"
brew "diffutils"
brew "fd"
brew "findutils"
brew "fzf"
brew "gawk"
brew "git-delta"
brew "gnu-sed"
brew "gnu-tar"
brew "gpatch"
brew "grep"
brew "jq"
brew "psgrep"
brew "ripgrep"

# languages/tools
brew "cmake"
brew "gh"
brew "make"
brew "n"
brew "pnpm"
brew "python"
brew "ruby"
brew "rust"

# media
brew "ffmpeg"
brew "imagemagick"
brew "optipng"
brew "uni"
brew "webp"

# mytools
brew "awscli"
brew "git-lfs"
brew "m-cli"
brew "mariadb"
brew "postgresql@15"
brew "redis"
brew "tlrc"
brew "vroom"
brew "watchman"

# brew "git"
# brew "git-extras"

# misc
brew "grip"
brew "mole"
